baseURL = "http://example.org/"
languageCode = "en-us"
theme = ""
title = ""
sectionPagesMenu = "main"
[menu]

  [[menu.main]]
    identifier = "homepage"
    name = "homepage"
    url = "/"
    weight = 100

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 101

  [[menu.main]]
    identifier = "locations"
    name = "locations"
    url = "/locations/"
    weight = 102
    
  [[menu.main]]
    identifier = "events"
    name = "events"
    url = "/events/"
    weight = 103

  [[menu.main]]
    identifier = "menu"
    name = "menu"
    url = "/menu/"
    weight = 104

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog/"
    weight = 105

  [[menu.main]]
    identifier = "careers"
    name = "careers"
    url = "/careers/"
    weight = 106

